### ISSUE TITLE
Spice conformers indexing is not correct 

### ISSUE THREAD

**Issue by FNTwin** [OpenDrugDiscovery/openQDC#23]
While computing statistics I got some errors on processing the Spice dataset and after some debugging I found that the indexing for a particular entry is not correct (at least I find it for that entry but this could be an issue on other entries or other datasets).

As it is now:
The conformer idxs for a single unique molecules are stored as repeated int as a list in the `data["name"]["inv_indices"]`
The idx represents the idx in data while the argidx is used to get back the unique name of the molecule and this makes the conformers contiguous in the memmap.

```python
data["name"]["inv_indices"] = [182, 182, 182 , 4,4,..., 1, 1, ... ]

conf_182 = [0,1,2]
``` 

For the unique molecule denominated `[H:3][C:1]#[C:2][H:4].[Na+:5]` I found that the idxs to retrieve the molecule informations are not contiguous:

```python
idxs=[709400, 709401, 709402, 709403, 709404, 
735379, 735380, 735381, 735382, 735383, 735384, 735385, 735386, 735387, 735388, 735389, 735390, 735391, 735392, 735393]
name_idx = 15917
``` 

This is a big problem because for lots of statistics I need to do operations on the data chunks defined by the conformers indexes of unique molecules. Furthermore, this kind of error is strange and shouldn't be present with the way we intended to store data.

**Comment by prtos** [comment]
The indexing is not incorrect! we do not expect the confs of a molecule to be contiguous
