### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by shenoynikhil** [OpenDrugDiscovery/openQDC#7]
Some known issues
- [x] Hydrogens are not loaded by default in QMUgs
- [x] Spice forces are negative of `dft_total_gradient`

**Comment by FNTwin** [comment]
> Hydrogens are not loaded by default in QMUgs

We should check if the energy calculated in QMUGS is with or without hydrogens

**Comment by shenoynikhil** [comment]
#8 resolves both the issues.
